{
 "title": "MicroProfile Metrics",
 "description": "Visualize all MicroProfile Metrics for your MicroProfile application",
 "tags": [
  "java",
  "microprofile",
  "smallrye"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(base_thread_count, env)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(base_thread_count{env=\"$env\"}, job)"
   },
   {
    "name": "app_kubernetes_io_instance",
    "label": "app_kubernetes_io_instance",
    "query": "label_values(base_thread_count{env=\"$env\",job=\"$job\"}, app_kubernetes_io_instance)"
   }
  ]
 },
 "panels": [
  { "title": "MicroProfile App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "MicroProfile Vendor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "System Cpu Load",
   "type": "stat",
   "description": "Display the \"recent cpu usage\" for the whole system. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that all CPUs were idle during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running 100% of the time during the recent period being observed. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the system. If the system recent cpu usage is not available, the method returns a negative value.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "vendor_system_cpu_load{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  { "title": "MicroProfile Base Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Currently Loaded Class Count",
   "type": "stat",
   "description": "Displays the number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Total Loaded Class Count",
   "type": "graph",
   "description": "Displays the total number of classes that have been loaded since the JVM has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total_total{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Total Unloaded Class Count",
   "type": "graph",
   "description": "Displays the total number of classes unloaded since the JVM has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total_total{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Available Processors",
   "type": "stat",
   "description": "Displays the number of processors available to the JVM. This value may change during a particular invocation of the virtual machine.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "stat",
   "description": "Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platform where it is expensive to implement this method.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "description": "Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The JVM implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_total{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "description": "Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total_total{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "description": "Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "HeapMemory Committed",
   "type": "graph",
   "description": "Displays the amount of memory in bytes that is committed for the JVM to use.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "NonHeapMemory Committed",
   "type": "graph",
   "description": "Displays the amount of memory in bytes that is committed for the JVM to use.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_committedNonHeap_bytes{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "HeapMemory Max Usage",
   "type": "graph",
   "description": "Displays the maximum amount of memory in bytes that can be used for HeapMemory.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "NonHeapMemory Max Usage",
   "type": "graph",
   "description": "Displays the maximum amount of memory in bytes that can be used for NonHeapMemory.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_maxNonHeap_bytes{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "HeapMemory Used",
   "type": "graph",
   "description": "Displays the amount of used memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "NonHeapMemory Used",
   "type": "graph",
   "description": "Displays the amount of used memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedNonHeap_bytes{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Current Thread count",
   "type": "stat",
   "description": "Displays the current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_thread_count{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Daemon Thread Count",
   "type": "stat",
   "description": "Displays the current number of live daemon threads.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_thread_daemon_count{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Peak Thread Count",
   "type": "stat",
   "description": "Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_thread_max_count{env=\"$env\",job=\"$job\",app_kubernetes_io_instance=~\"$app_kubernetes_io_instance\"}",
     "legendFormat": "{{job}}/{{app_kubernetes_io_instance}} "
    }
   ]
  }
 ]
}